name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.2", "8.3"]
    steps:
      - run: sudo apt-get install libzip-dev

      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - run: php --ini

      - uses: php-actions/composer@v6

      - run: bash docker/start.sh

      - run: vendor/bin/phpunit --debug --testsuite Tests

